# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish

on:
  release:
    types: [prereleased, released]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Read version
        id: read_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'gradle.properties'
          property: 'version'
      - name: NPM-Version
        uses: Reedyuk/NPM-Version@1.0.1
        with:
          version: ${{ steps.read_version.outputs.value }}
          package: "firebase-app/"
      - name: NPM-Version
        uses: Reedyuk/NPM-Version@1.0.1
        with:
          version: ${{ steps.read_version.outputs.value }}
          package: "firebase-auth/"
      - name: NPM-Version
        uses: Reedyuk/NPM-Version@1.0.1
        with:
          version: ${{ steps.read_version.outputs.value }}
          package: "firebase-common/"
      - name: NPM-Version
        uses: Reedyuk/NPM-Version@1.0.1
        with:
          version: ${{ steps.read_version.outputs.value }}
          package: "firebase-database/"
      - name: NPM-Version
        uses: Reedyuk/NPM-Version@1.0.1
        with:
          version: ${{ steps.read_version.outputs.value }}
          package: "firebase-firestore/"
      - name: NPM-Version
        uses: Reedyuk/NPM-Version@1.0.1
        with:
          version: ${{ steps.read_version.outputs.value }}
          package: "firebase-functions/"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Retrieve cache key
        id: cache-key
        uses: actions/cache@v2
        with:
          path: build/Firebase-6.17.0.zip
          key: key-Firebase-6.17.0
          restore-keys: key-Firebase-6.17.0
      - name: Expand Zip
        if: steps.cache-key.outputs.cache-hit == 'true'
        run: unzip build/Firebase-6.17.0.zip -d build
      - name: Download Unzip Firebase
        run: ./gradlew unzipIOSFirebase
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish
        env:
          sonatypeUsername: ${{ secrets.SONATYPEUSERNAME }}
          sonatypePassword: ${{ secrets.SONATYPEPASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}
